# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - master
    - releases/*
    - hotfix/*

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: buildAndPush
        containerRegistry: 'Github'
        repository: 'bsperduto/s2i-php-fpm-container/php-72-fpm-centos7'
        dockerfile: '$(Build.SourcesDirectory)/7.2/Dockerfile'
        tags: |
          $(tag)
          $(Build.SourceBranchName)
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: buildAndPush
        containerRegistry: 'Github'
        repository: 'bsperduto/s2i-php-fpm-container/php-72-fpm-ubi8'
        dockerfile: '$(Build.SourcesDirectory)/7.2/Dockerfile.ubi8'
        tags: |
          $(tag)
          $(Build.SourceBranchName)